# Generated by Django 3.0.3 on 2020-02-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_basket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='products',
        ),
        migrations.CreateModel(
            name='BasketProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Basket')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Products')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(through='employees.BasketProducts', to='employees.Products'),
        ),
    ]
